services:
  - type: web
    name: medai-backend
    runtime: python
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cpu
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONPATH
        value: ".."
      - key: PREPROCESSING_MODE
        value: "opencv" # Disable YOLO to save RAM on 512MB instance
      - key: TORCH_THREADS
        value: "1" # Limit threading overhead
      - key: MALLOC_ARENA_MAX
        value: "2" # Avoid memory fragmentation
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: USE_MONGODB
        value: "false"
